<script setup lang="ts">
	useSeoMeta({
		title: "Your Meal Plan — Mealwise",
		description: "Your personalised weekly meal plan and shopping list, generated by AI."
	});

	useHead({
		meta: [{ name: "robots", content: "noindex" }]
	});
</script>
<template>
	<PlanScreen />
</template>
